FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye

ADD .zshrc /home/vscode/.
ADD git-prompt.sh /home/vscode/.
ADD .oh-my-zsh/custom/themes/sully.zsh-theme /home/vscode/.oh-my-zsh/custom/themes/.

ENV SHELL /bin/zsh